# Generated by Django 3.0.3 on 2020-03-31 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('permission', models.IntegerField()),
                ('manage_class', models.CharField(max_length=1)),
                ('password', models.CharField(default='123456', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Change_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=6)),
                ('before_class_name', models.CharField(max_length=6)),
                ('teacher_evaluate', models.TextField(default=' ')),
                ('change_class_num', models.IntegerField()),
                ('status', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=1)),
                ('class_name', models.CharField(max_length=6)),
                ('profession', models.CharField(max_length=8)),
                ('teacher_name', models.CharField(max_length=15)),
                ('teach_name', models.CharField(max_length=15)),
                ('password', models.CharField(default='123456', max_length=15)),
                ('permission', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sug_content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_num', models.CharField(max_length=18, unique=True)),
                ('age', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=30)),
                ('come_of_enrollment', models.CharField(max_length=20)),
                ('recruiter', models.CharField(max_length=15)),
                ('tel_num', models.CharField(max_length=11)),
                ('parent_name', models.CharField(max_length=15)),
                ('parent_tel_num', models.CharField(max_length=11)),
                ('tuition', models.CharField(max_length=6)),
                ('loans', models.CharField(max_length=6)),
                ('credit', models.IntegerField()),
                ('s_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stu_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='School_expression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('punish', models.TextField()),
                ('result', models.CharField(max_length=3)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_time', models.CharField(max_length=3)),
                ('write_points', models.IntegerField()),
                ('competer_points', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_school',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='0', max_length=2)),
                ('s_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stu_app.Student')),
            ],
        ),
    ]
