# Generated by Django 3.0.3 on 2020-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_class',
            name='res',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
