# Generated by Django 3.0.3 on 2020-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0002_change_class_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_expression',
            name='status',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
