# Generated by Django 3.0.3 on 2020-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0002_remove_administrator_manage_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='exam_time',
            field=models.CharField(max_length=10),
        ),
    ]
