# Generated by Django 3.0.3 on 2020-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0004_school_expression_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_msg',
            name='credit',
        ),
        migrations.AddField(
            model_name='student',
            name='credit',
            field=models.IntegerField(default=100),
        ),
    ]
