# Generated by Django 3.0.3 on 2020-04-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0005_auto_20200408_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_class',
            name='teacher_evaluate',
        ),
        migrations.AlterField(
            model_name='school_expression',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
