# Generated by Django 3.0.3 on 2020-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0008_auto_20200410_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropout',
            name='dropout',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
